# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 38057ef6d4daba70bd3952721b029247cd2efd7f60572aa59fe3744ad5c404e6877e116372910e916dde48630693bd11ec83e6569c856d4f25fa2683da8f2243

test:
  secret_key_base: 4fec578ac639597fe8f0480d4da802b37165d3f3fd0677680c0b99cadda4c3f79db93968f989ac7fa52b1fb35eceee39df5ed630f760465d26a9e0b84ad6f198

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
